import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { Toaster } from '@shadcn/index';
import { Open_Sans } from 'next/font/google';

const opensans = Open_Sans({ subsets: ['latin'], variable: '--font-opensans' });

export const metadata = {
  // To Do: Update the title and description
  title: 'Welcome to auth',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${opensans.variable}`}>
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
