import './globals.css';
import { Toaster } from '@shadcn/index';
import { ClerkProvider } from '@clerk/nextjs';
import { Caveat, Open_Sans } from 'next/font/google';

const caveat = Caveat({ subsets: ['latin'], variable: '--font-caveat' });
const opensans = Open_Sans({ subsets: ['latin'], variable: '--font-opensans' });

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${caveat.variable} ${opensans.variable}`}>
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
